---
title: "Project_Proposal"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

  Our project aims to examine the effect of “sin taxes,” specifically taxes on tobacco, on consumption, as well as creating visualizations of the relationship between the two. Research already exists supporting the idea that higher taxes on tobacco products will reduce usage, so our aim is simply to confirm these claims and create useful visualizations of the relationship. Research will also be done about the effects of geographical proximity to Native American Reservations on consumption, as cigarettes sold on reservations are not subject to the same domestic taxes as those sold on US lands. 							
  Studying this idea is important as tobacco use is the leading cause of preventable deaths in the US. If government policy can reduce tobacco use it would save and improve many lives, as well as reducing healthcare costs across the board. For this reason studying the relationship between tax policy and tobacco use is important. Critics of such taxes often point out that these taxes are regressive and paternalistic, and that the state should not be able to decide what an individual chooses to consume. While there is some merit to this argument, tobacco products do have negative externalities that are not reflected in the market price, namely second hand smoke and unnecessary strain on the healthcare system. 
  
  Our model will examine the relationship between tax rates and tobacco consumption by state. We will be using a linear regression to test our null hypothesis: an increase in tobacco tax will have no effect on tobacco consumption. Previous data and research has already falsified this hypothesis, so we expect that our results will do the same. A linear regression will be the most practical model for examining the relationship between the two sin tax and tobacco as the variables are all continuous. In our model we will include percentage of smokers as the dependent variables and have the price of tobacco, tax on tobacco, household income, and proximity to a Native American reservation as the explanatory variables. We include household income as we think it is likely that lower income families may consume more tobacco than higher income ones, all else being equal. This will lead to lower income families feeling the effects of sin taxes more, but also hopefully curtailing consumption at higher rates. Overall we hypothesize that the demand curve for cigarettes will be inelastic as smoking is addictive, however simple laws of supply and demand will still hold and with an increase in sin tax, tobacco consumption will gradually diminish over time showing a negative relationship. 
